name: CA Marks Checker 
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  selenium-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for faster checkout
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'  # Use built-in pip caching (faster than manual cache)
      
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
      
      - name: Run Script
        env:
          REGISTRATION_NUMBER: ${{ secrets.REGISTRATION_NUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
